export const courses = [
  {
    id: 'cs-124',
    code: 'CS 124',
    name: 'Intro to Computer Science I',
    credits: 3,
    avgGpa: 3.52,
    instructor: 'Challen, G',
    isExcellent: true,
  },
  {
    id: 'cs-128',
    code: 'CS 128',
    name: 'Intro to Computer Science II',
    credits: 3,
    avgGpa: 3.41,
    instructor: 'Nowak, M',
    isExcellent: true,
  },
  {
    id: 'cs-225',
    code: 'CS 225',
    name: 'Data Structures',
    credits: 4,
    avgGpa: 3.28,
    instructor: 'Evans, G',
    isExcellent: true,
  },
  {
    id: 'ece-391',
    code: 'ECE 391',
    name: 'Computer Systems Engineering',
    credits: 4,
    avgGpa: 2.85,
    instructor: 'Kalbarczyk, Z',
    isExcellent: false,
  },
  {
    id: 'math-241',
    code: 'MATH 241',
    name: 'Calculus III',
    credits: 4,
    avgGpa: 2.91,
    instructor: 'Dunfield, N',
    isExcellent: true,
  },
  {
    id: 'cs-440',
    code: 'CS 440',
    name: 'Artificial Intelligence',
    credits: 3,
    avgGpa: 3.45,
    instructor: 'Lazier, S',
    isExcellent: false,
  },
  {
    id: 'cs-105',
    code: 'CS 105',
    name: 'Intro to Computing',
    credits: 3,
    avgGpa: 3.82,
    instructor: 'Harris, A',
    isExcellent: true,
  },
  {
    id: 'stat-400',
    code: 'STAT 400',
    name: 'Statistics and Probability I',
    credits: 4,
    avgGpa: 3.12,
    instructor: 'Unger, D',
    isExcellent: false,
  },
  {
    id: 'econ-102',
    code: 'ECON 102',
    name: 'Microeconomic Principles',
    credits: 3,
    avgGpa: 3.65,
    instructor: 'Vasquez, J',
    isExcellent: true,
  },
  {
    id: 'phys-211',
    code: 'PHYS 211',
    name: 'University Physics: Mechanics',
    credits: 4,
    avgGpa: 2.78,
    instructor: 'Stelzer, T',
    isExcellent: true,
  }
];
